[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[package]
name = "fsspec"
version = "dynamic"

[package.build]
backend = { name = "pixi-build-python", version = "*" }
source = { git = "https://github.com/fsspec/filesystem_spec" }

[package.host-dependencies]
hatchling = "*"
hatch-vcs = "*"

[package.run-dependencies]
python = "*"
